version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - /var/lib/postgresql/data/
  web:
    build:
      context: ../backend/foodgram
      dockerfile: Dockerfile
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - web
      - frontend
volumes:
  frontend_value:
  static_value:
  media_value:
