version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
  web:
    image: t1m4k/foodgram_backend:v0.2
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - db
  frontend:
    image: t1m4k/foodgram_frontend:v0.1
    volumes:
      - ../frontend/:/app/result_build/
    env_file:
      - .env
    depends_on:
      - web
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - web
      - frontend
volumes:
  frontend_value:
  static_value:
  media_value:
